# Generated by Django 5.1.3 on 2024-11-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autho',
            new_name='author',
        ),
    ]
